# Generated by Django 2.0.5 on 2018-05-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rental_type', models.SmallIntegerField(choices=[(0, 'Hour'), (1, 'Day'), (2, 'Week')])),
                ('rental_time', models.PositiveSmallIntegerField()),
                ('bike_qty', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
